### PR TITLE
Add sample workflow snippet

### PR DESCRIPTION
**Pull request by koral--**

### CODE REVIEW

**Comment by jonasbark** [comment]
I'm wondering: which project type is this supposed to be used on? React Native? Xamarin? If so, which stack contains both up to date Android Studio + Xcode installs?

**Comment by koral--** [comment]
It seems that there is no stack with out of the box up-to date tools for both platforms. There was a discussion about it: https://discuss.bitrise.io/t/xcode-android-sdk-combined-stack/242/5

If you prefer to use single stack, hybrid stack for Xamarin seems to be a good candidate.
Another option (not available yet at the time when linked thread was active) is to use separate workflows for each platform. Currently you can assign stack for a particular workflow, not for the whole app like before.
You can use for example Trigger Bitrise Workflow step, to trigger the build for a second platform.

**Comment by jonasbark** [comment]
Thanks for the hint - great to learn about it!
I found out that https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-vs4mac-stable.log (Hybrid (Xamarin, Ionic, ...) on macOS, includes Visual Studio for Mac, Stable channel) actually contains up to date versions of Xcode & Android Studio 👍

**Comment by koral--** [comment]
Android NDK version is very old there: https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-vs4mac-stable.log#L740
On Linux Stack it is updated weekly.

**Pull request merged**
